// <auto-generated />
namespace Gym_Management.MigrationsManagement
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Skuska : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Skuska));
        
        string IMigrationMetadata.Id
        {
            get { return "202211211938460_Skuska"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
